name: Frontend tests
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  frontend-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
    - uses: actions/checkout@v2

    - uses: browser-actions/setup-chrome@v1

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
#        cache-dependency-path: package-lock.json
      timeout-minutes: 10

    - name: Update npm
      run: npm install -g npm@10.8.2

    - name: Install dependencies
      run: npm ci

    - name: Create env file
      run: touch .env
#      run: |
#        echo API_BASE_URL=http://localhost/api/v1 > .env
#        echo GEOSERVER_BASE_URL=http://localhost/geoserver >> .env
#        echo SENTRY_DSN= >> .env

    - name: Launching tests
      run: CHROME_BIN=$(which chrome) npm run test

#    - name: Building javascript
#      run: CHROME_BIN=$(which chrome) npm run build
